# Generated by Django 2.2.17 on 2020-11-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'article')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
