# Generated by Django 2.2.6 on 2020-11-06 08:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_auto_20201106_0832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Cart_bd',
        ),
    ]
